name: Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    # Step 1 拉代码
    - name: Checkout
      uses: actions/checkout@v4


    # Step 2 登录 AWS
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:

        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region: ${{ secrets.AWS_REGION }}


    # Step 3 登录 ECR
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    # Step 4 构建镜像
    - name: Build Docker Image

      run: |

        docker build \
        -t mine_project_image \
        -f docker/Dockerfile \
        .


    # Step 5 打 tag
    - name: Tag Image

      run: |

        docker tag mine_project_image:latest \
        ${{ steps.login-ecr.outputs.registry }}/mine_project_image:latest


    # Step 6 Push
    - name: Push Image

      run: |

        docker push \
        ${{ steps.login-ecr.outputs.registry }}/mine_project_image:latest